designmynight/designmynight-developers

hugo/content/booking-api/index.md

Fix dev url

---

hugo/config.toml
hugo/content/booking-api/index.md
hugo/content/offers-api/index.md

Does this make sense? Let me know if I've rambled off anywhere haha.
Also, I couldn't run any of the gulp tasks due to an error with the `browser-sync` plugin. But looking at the repository, it doesn't look like I need to build anything when adding new content. Is that right?

Created documentation for offers API

---

README.md

fyi @alasdairmackenzie - Details that were in the [PR](#4) are now in the readme

docs: included more details in the README

---

site/content/bookings-search/index.md
site/content/users-api/index.md

Fixes designmynight/dmn#21766.
(Sorry, most of my changes for this got accidentally merged in with #4).
[Users](http://developers.designmynight.com/users-api/) and [Bookings Search](http://developers.designmynight.com/bookings-search/) now include:
* Supported Output Formats
* Pagination Instructions
* Allowed filter parameters
* Example requests for all functionality

docs: Bookings and Users endpoint

---

site/content/api/booking-api/index.md

Fixes designmynight/dmn#24245.
Wrote documentation for the `booking-rules` endpoint

docs: Added documentation on the booking-rules endpoint

---

site/content/api/booking-api/index.md

Fixes designmynight/dmn#24214
Documentation now includes information on storing bookings/enquiries by posting to the `/bookings` endpoint.

feat: Posting to the /bookings endpoint

---

site/content/api/booking-api/index.md

docs: removed reference to legacy partner_data_permission param

---

site/content/api/booking-api/index.md
site/content/api/users-api/index.md

Closes designmynight/dmn#26032
Updated documentation to explain how to pass in the new marketing preferences for bookings and updating the marketing preferences for existing users.
also fyi @StevePorter92

docs: Marketing Preferences

---

site/content/api/bookings-search/index.md

docs: included line about the `start_time` filter

---

site/content/api/venue-groups/index.md

feat: document recently added capabilities

---

package-lock.json
site/content/tonic/ticket-widget/index.md

closes designmynight/dmn#26878
fyi @samc05

docs: update the ticket widget docs to v3

---

.gitignore
site/config.toml
site/content/soda/partner-widget/index.md

For designmynight/dmn#27159
@robbytaylor , I'm about to head off.  Once approved can you merge and let Debbie know it's live at http://developers.designmynight.com/soda/partner-widget/ please

docs: soda widget

---

site/content/api/booking-api/index.md

Closes designmynight/dmn#27488

docs: Updating an existing booking

---

site/content/api/booking-api/index.md

docs: Added info about submitting packages

---

site/content/api/bookings-search/index.md

fyi @StevePorter92 @willtj 
for https://github.com/designmynight/dmn/issues/27876

docs: wrote examples on using the fields parameter

---

site/content/v2-widget-docs.md

doc: Include docs about custom-source widget attribute

---

site/content/api/bookings-search/index.md

Closes designmynight/dmn#30001

docs: document the assigned_areas field

---

site/config.toml
site/content/collins/customer-widget/index.md

@danjohnson95 this doesn't look like it's going to launch super soon so no rush to review but would be helpful if you can cast your eye over it.
@designmynight/collins-account-managers at some point you'll end up supporting the new customer signup widget - this is mainly just an FYI for now if you want to check the documentation that we'll be putting on developers.designmynight.com for it.

Documentation for signup widget

---

site/content/api/booking-api/index.md
site/content/api/bookings-search/index.md
site/content/api/users-api/index.md
site/content/api/venue-groups/index.md

fix: broken links

---

site/content/collins/v2-widget-docs.md

Documents the methods added in https://github.com/designmynight/booking-form/pull/136 for https://github.com/designmynight/dmn/issues/35405

docs: Added docs for min/max guests
